version: '3.9'

services:
  postgres:
    image: vicens2/postgres:15-alpine
    # ou image: postgres:15-alpine (officielle)
    
  backend:
    image: vicens2/vote-backend:latest
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      
  frontend:
    image: vicens2/vote-frontend:latest
    ports:
      - "80:80"