[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = tests/*.py tests/**/*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short


;  Command to run tests:
; pytest tests/ -v


; Command to run tests with coverage:
; pytest tests/ -v --cov=. --cov-report=html --cov-report=term-missing