# Generated by Django 4.2.16 on 2026-05-21 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('scrutins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulletin_chiffre', models.TextField()),
                ('signature', models.TextField()),
                ('hash_vote', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes_recus', to='scrutins.candidat')),
                ('scrutin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='scrutins.scrutin')),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
                'db_table': 'vote',
            },
        ),
        migrations.CreateModel(
            name='ElecteurScrutinVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vote', models.DateTimeField(auto_now_add=True)),
                ('electeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='accounts.electeur')),
                ('scrutin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='scrutins.scrutin')),
            ],
            options={
                'verbose_name': 'Participation électeur',
                'verbose_name_plural': 'Participations électeurs',
                'db_table': 'electeur_scrutin_vote',
                'unique_together': {('electeur', 'scrutin')},
            },
        ),
    ]
