# Generated by Django 4.2.16 on 2026-05-21 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeBlancheReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('filiere', models.CharField(choices=[('MECA', 'Mecatronique'), ('GTS', 'Genie telecommunication et systeme'), ('BAT', 'Genie civil -Batiments'), ('IIA', 'Informatique industriel et automatisme'), ('RSI', 'Reseaux et securite informatique'), ('GL', 'Génie Logiciel'), ('AUTRE', 'Autre')], max_length=20)),
                ('niveau', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], max_length=5)),
                ('a_cree_son_compte', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Référence liste blanche',
                'verbose_name_plural': 'Références liste blanche',
                'db_table': 'liste_blanche_reference',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Electeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('filiere', models.CharField(max_length=20)),
                ('niveau', models.CharField(max_length=5)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('ELIGIBLE', 'Eligible'), ('SUSPENDU', 'Suspendu')], default='EN_ATTENTE', max_length=20)),
                ('a_vote', models.BooleanField(default=False)),
                ('date_vote', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='electeur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Électeur',
                'verbose_name_plural': 'Électeurs',
                'db_table': 'electeur',
                'ordering': ['matricule'],
            },
        ),
    ]
