# Generated by Django 4.2.16 on 2026-05-21 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CONNEXION', 'Connexion'), ('INSCRIPTION', 'Inscription'), ('VOTE', 'Vote'), ('CREATION_SCRUTIN', 'Création scrutin'), ('OUVERTURE_SCRUTIN', 'Ouverture scrutin'), ('CLOTURE_SCRUTIN', 'Clôture scrutin'), ('SUSPENSION_ELECTEUR', 'Suspension électeur'), ('VALIDATION_ELECTEUR', 'Validation électeur'), ('IMPORT_LISTE_BLANCHE', 'Import liste blanche')], max_length=50)),
                ('details', models.JSONField(blank=True, null=True)),
                ('hash_precedent', models.CharField(max_length=64)),
                ('hash_courant', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Log d'audit",
                'verbose_name_plural': "Logs d'audit",
                'db_table': 'log_audit',
                'ordering': ['-created_at'],
            },
        ),
    ]
