# Generated by Django 4.2.16 on 2026-05-21 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrutin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('OUVERT', 'Ouvert'), ('CLOTURE', 'Clôturé')], default='BROUILLON', max_length=20)),
                ('filiere_cible', models.CharField(blank=True, max_length=20, null=True)),
                ('niveau_cible', models.CharField(blank=True, max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scrutins_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scrutin',
                'verbose_name_plural': 'Scrutins',
                'db_table': 'scrutin',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidats/')),
                ('programme', models.TextField(blank=True, null=True)),
                ('est_vote_blanc', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scrutin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidats', to='scrutins.scrutin')),
            ],
            options={
                'verbose_name': 'Candidat',
                'verbose_name_plural': 'Candidats',
                'db_table': 'candidat',
                'ordering': ['est_vote_blanc', 'nom'],
            },
        ),
    ]
