# Generated by Django 4.2.16 on 2026-05-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrutins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
    ]
